###  Pinkbook2017_3.4

In [1]:
from databaker.framework import *

In [2]:
import pandas as pd

In [3]:
import io
import requests
from pathlib import Path

In [4]:
Url = 'https://drive.google.com/uc?export=download&id=16CpeYtvRxkvyt2RUkSAzTBGEJX_DnNLm'

In [5]:
df = pd.read_excel(Url, sheetname='3.4', header=None)

In [6]:
df

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,3.4,Insurance and pension services1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Â£ million
2,NaN,NaN,NaN,1997,1998,1999,2000,2001,2002,2003,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,,Exports (Credits),,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,,Direct insurance,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,,Life insurance,FJEU,488,846,1569,1423,2182,800,13,...,-526,-264,-619,333,313,429,2842,4056,555,-35
8,,Freight insurance,FJJL,82,76,47,41,49,80,129,...,141,133,230,538,753,511,585,577,494,495
9,,Other direct insurance2,FJEW,3235,2353,1170,1153,998,2364,5398,...,10112,9661,11513,8419,10548,15681,13456,11041,11054,13924
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,,Total direct insurance,MSH9,3805,3275,2786,2617,3229,3244,5540,...,9727,9530,11124,9290,11614,16621,16883,15674,12103,14384
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,,Reinsurance,FJEX,718,331,-49,-296,1011,1473,2241,...,399,2037,2136,698,564,420,386,633,484,493
14,,Auxiliary insurance services,FJEY,972,1167,1072,1106,1012,1087,1114,...,1546,1686,1935,1909,2295,2334,2436,2773,2227,2753
15,,Pensions and standardised guarantees,MSI2,6,-8,-12,-6,-8,-3,-5,...,24,-11,-34,-,-,-,-,-,-,-
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,,Total3,FJPJ,5501,4765,3797,3421,5244,5801,8890,...,11696,13242,15161,11897,14473,19375,19705,19080,14814,17630
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,,Imports (Debits),,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,,Direct insurance,MSI4,364,335,364,399,512,766,786,...,1031,1119,1017,1578,2328,1561,1894,1932,12,12
22,,Reinsurance,FJFD,706,648,706,772,992,1483,3079,...,998,539,2960,1509,-,-,-,-,-,-
23,,Auxiliary insurance services,FJFE,-,-,-,-,-,-,-,...,-,-,-,-,-,-,148,337,179,183
24,,Pensions and standardised guarantees,MSI5,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,3,4
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,,Total,FJRB,1070,983,1070,1171,1504,2249,3865,...,2029,1658,3977,3087,2328,1561,2042,2269,194,199
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,,Balances,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,,Direct insurance,MSH2,3441,2940,2422,2218,2717,2478,4754,...,8696,8411,10107,7712,9286,15060,14989,13742,12091,14372
31,,Reinsurance,FJJN,12,-317,-755,-1068,19,-10,-838,...,-599,1498,-824,-811,564,420,386,633,484,493
32,,Auxiliary insurance services,FJJO,972,1167,1072,1106,1012,1087,1114,...,1546,1686,1935,1909,2295,2334,2288,2436,2048,2570
33,,Pensions and standardised guarantees,MSH3,6,-8,-12,-6,-8,-3,-5,...,24,-11,-34,-,-,-,-,-,-3,-4
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,,Total,FJSV,4431,3782,2727,2250,3740,3552,5025,...,9667,11584,11184,8810,12145,17814,17663,16811,14620,17431
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,1,The latest year's data for trade in services ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,figures are subject to annual benchmarking.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2,Other direct insurance by UK insurance compan...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,"facultative reinsurance on marine, aviation a...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,3,Exports of insurance services are net of expe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,insurance companies.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Source:,Office for National Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.to_excel('PB2017_3.4.xls',index=False)

In [8]:
tab = loadxlstabs('PB2017_3.4.xls')

Loading PB2017_3.4.xls which has size 13824 bytes
Table names: ['Sheet1']

In [9]:
tab = tab[0]
savepreviewhtml(tab)

In [10]:
observations = tab.excel_ref('D9').expand(DOWN).expand(RIGHT).is_not_blank()

In [11]:
Code = tab.excel_ref('C9').expand(DOWN).is_not_blank()

In [12]:
Year = tab.excel_ref('D4').expand(RIGHT).is_not_blank()

In [15]:
Commerce = tab.excel_ref('B').expand(DOWN).by_index([6,21,30]) - tab.excel_ref('B38').expand(DOWN)

In [17]:
InsuranceRevenue = tab.excel_ref('B').expand(DOWN).is_not_blank().is_not_whitespace() - Commerce - tab.excel_ref('B2').expand(UP)

In [18]:
Currency = tab.excel_ref('W3')

In [20]:
Dimensions = [
            HDimConst('GEOG', 'K02000001'),
            HDim(Year,'Year', DIRECTLY,ABOVE),
            HDim(Code,'Code Identifier',DIRECTLY,LEFT),
            HDimConst('Currency', 'GBP(millions)'),            
            HDim(InsuranceRevenue, 'Insurance Revenue', DIRECTLY, LEFT),
            HDim(Commerce, 'Commerce', CLOSEST, ABOVE)    
]

In [21]:
c1 = ConversionSegment(observations, Dimensions, processTIMEUNIT=True)

In [22]:
savepreviewhtml(c1)

In [23]:
new_table = c1.topandas()
new_table

,OBS,DATAMARKER,GEOG,Year,Code Identifier,Currency,Insurance Revenue,Commerce
0,488,NaN,K02000001,1997.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
1,846,NaN,K02000001,1998.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
2,1569,NaN,K02000001,1999.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
3,1423,NaN,K02000001,2000.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
4,2182,NaN,K02000001,2001.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
5,800,NaN,K02000001,2002.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
6,13,NaN,K02000001,2003.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
7,-717,NaN,K02000001,2004.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
8,-1498,NaN,K02000001,2005.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
9,-1261,NaN,K02000001,2006.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
10,-526,NaN,K02000001,2007.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
11,-264,NaN,K02000001,2008.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
12,-619,NaN,K02000001,2009.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
13,333,NaN,K02000001,2010.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
14,313,NaN,K02000001,2011.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
15,429,NaN,K02000001,2012.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
16,2842,NaN,K02000001,2013.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
17,4056,NaN,K02000001,2014.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
18,555,NaN,K02000001,2015.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
19,-35,NaN,K02000001,2016.0,FJEU,GBP(millions),Life insurance,Exports (Credits)
20,82,NaN,K02000001,1997.0,FJJL,GBP(millions),Freight insurance,Exports (Credits)
21,76,NaN,K02000001,1998.0,FJJL,GBP(millions),Freight insurance,Exports (Credits)
22,47,NaN,K02000001,1999.0,FJJL,GBP(millions),Freight insurance,Exports (Credits)
23,41,NaN,K02000001,2000.0,FJJL,GBP(millions),Freight insurance,Exports (Credits)
24,49,NaN,K02000001,2001.0,FJJL,GBP(millions),Freight insurance,Exports (Credits)
25,80,NaN,K02000001,2002.0,FJJL,GBP(millions),Freight insurance,Exports (Credits)
26,129,NaN,K02000001,2003.0,FJJL,GBP(millions),Freight insurance,Exports (Credits)
27,90,NaN,K02000001,2004.0,FJJL,GBP(millions),Freight insurance,Exports (Credits)
28,72,NaN,K02000001,2005.0,FJJL,GBP(millions),Freight insurance,Exports (Credits)
29,43,NaN,K02000001,2006.0,FJJL,GBP(millions),Freight insurance,Exports (Credits)
...,...,...,...,...,...,...,...,...
330,24,NaN,K02000001,2007.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances
331,-11,NaN,K02000001,2008.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances
332,-34,NaN,K02000001,2009.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances
333,,-,K02000001,2010.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances
334,,-,K02000001,2011.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances
335,,-,K02000001,2012.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances
336,,-,K02000001,2013.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances
337,,-,K02000001,2014.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances
338,-3,NaN,K02000001,2015.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances
339,-4,NaN,K02000001,2016.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances
340,4431,NaN,K02000001,1997.0,FJSV,GBP(millions),Total,Balances
341,3782,NaN,K02000001,1998.0,FJSV,GBP(millions),Total,Balances
342,2727,NaN,K02000001,1999.0,FJSV,GBP(millions),Total,Balances
343,2250,NaN,K02000001,2000.0,FJSV,GBP(millions),Total,Balances
344,3740,NaN,K02000001,2001.0,FJSV,GBP(millions),Total,Balances
345,3552,NaN,K02000001,2002.0,FJSV,GBP(millions),Total,Balances
346,5025,NaN,K02000001,2003.0,FJSV,GBP(millions),Total,Balances
347,3792,NaN,K02000001,2004.0,FJSV,GBP(millions),Total,Balances
348,8011,NaN,K02000001,2005.0,FJSV,GBP(millions),Total,Balances
349,9570,NaN,K02000001,2006.0,FJSV,GBP(millions),Total,Balances
350,9667,NaN,K02000001,2007.0,FJSV,GBP(millions),Total,Balances
351,11584,NaN,K02000001,2008.0,FJSV,GBP(millions),Total,Balances
352,11184,NaN,K02000001,2009.0,FJSV,GBP(millions),Total,Balances
353,8810,NaN,K02000001,2010.0,FJSV,GBP(millions),Total,Balances
354,12145,NaN,K02000001,2011.0,FJSV,GBP(millions),Total,Balances
355,17814,NaN,K02000001,2012.0,FJSV,GBP(millions),Total,Balances
356,17663,NaN,K02000001,2013.0,FJSV,GBP(millions),Total,Balances
357,16811,NaN,K02000001,2014.0,FJSV,GBP(millions),Total,Balances
358,14620,NaN,K02000001,2015.0,FJSV,GBP(millions),Total,Balances
359,17431,NaN,K02000001,2016.0,FJSV,GBP(millions),Total,Balances

In [24]:
new_table = new_table.drop('DATAMARKER', axis=1)

In [25]:
new_table['TIME'] = new_table['Year'].map(lambda cell:cell.replace('.0', ''))
new_table

,OBS,GEOG,Year,Code Identifier,Currency,Insurance Revenue,Commerce,TIME
0,488,K02000001,1997.0,FJEU,GBP(millions),Life insurance,Exports (Credits),1997
1,846,K02000001,1998.0,FJEU,GBP(millions),Life insurance,Exports (Credits),1998
2,1569,K02000001,1999.0,FJEU,GBP(millions),Life insurance,Exports (Credits),1999
3,1423,K02000001,2000.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2000
4,2182,K02000001,2001.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2001
5,800,K02000001,2002.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2002
6,13,K02000001,2003.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2003
7,-717,K02000001,2004.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2004
8,-1498,K02000001,2005.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2005
9,-1261,K02000001,2006.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2006
10,-526,K02000001,2007.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2007
11,-264,K02000001,2008.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2008
12,-619,K02000001,2009.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2009
13,333,K02000001,2010.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2010
14,313,K02000001,2011.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2011
15,429,K02000001,2012.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2012
16,2842,K02000001,2013.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2013
17,4056,K02000001,2014.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2014
18,555,K02000001,2015.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2015
19,-35,K02000001,2016.0,FJEU,GBP(millions),Life insurance,Exports (Credits),2016
20,82,K02000001,1997.0,FJJL,GBP(millions),Freight insurance,Exports (Credits),1997
21,76,K02000001,1998.0,FJJL,GBP(millions),Freight insurance,Exports (Credits),1998
22,47,K02000001,1999.0,FJJL,GBP(millions),Freight insurance,Exports (Credits),1999
23,41,K02000001,2000.0,FJJL,GBP(millions),Freight insurance,Exports (Credits),2000
24,49,K02000001,2001.0,FJJL,GBP(millions),Freight insurance,Exports (Credits),2001
25,80,K02000001,2002.0,FJJL,GBP(millions),Freight insurance,Exports (Credits),2002
26,129,K02000001,2003.0,FJJL,GBP(millions),Freight insurance,Exports (Credits),2003
27,90,K02000001,2004.0,FJJL,GBP(millions),Freight insurance,Exports (Credits),2004
28,72,K02000001,2005.0,FJJL,GBP(millions),Freight insurance,Exports (Credits),2005
29,43,K02000001,2006.0,FJJL,GBP(millions),Freight insurance,Exports (Credits),2006
...,...,...,...,...,...,...,...,...
330,24,K02000001,2007.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2007
331,-11,K02000001,2008.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2008
332,-34,K02000001,2009.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2009
333,,K02000001,2010.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2010
334,,K02000001,2011.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2011
335,,K02000001,2012.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2012
336,,K02000001,2013.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2013
337,,K02000001,2014.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2014
338,-3,K02000001,2015.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2015
339,-4,K02000001,2016.0,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2016
340,4431,K02000001,1997.0,FJSV,GBP(millions),Total,Balances,1997
341,3782,K02000001,1998.0,FJSV,GBP(millions),Total,Balances,1998
342,2727,K02000001,1999.0,FJSV,GBP(millions),Total,Balances,1999
343,2250,K02000001,2000.0,FJSV,GBP(millions),Total,Balances,2000
344,3740,K02000001,2001.0,FJSV,GBP(millions),Total,Balances,2001
345,3552,K02000001,2002.0,FJSV,GBP(millions),Total,Balances,2002
346,5025,K02000001,2003.0,FJSV,GBP(millions),Total,Balances,2003
347,3792,K02000001,2004.0,FJSV,GBP(millions),Total,Balances,2004
348,8011,K02000001,2005.0,FJSV,GBP(millions),Total,Balances,2005
349,9570,K02000001,2006.0,FJSV,GBP(millions),Total,Balances,2006
350,9667,K02000001,2007.0,FJSV,GBP(millions),Total,Balances,2007
351,11584,K02000001,2008.0,FJSV,GBP(millions),Total,Balances,2008
352,11184,K02000001,2009.0,FJSV,GBP(millions),Total,Balances,2009
353,8810,K02000001,2010.0,FJSV,GBP(millions),Total,Balances,2010
354,12145,K02000001,2011.0,FJSV,GBP(millions),Total,Balances,2011
355,17814,K02000001,2012.0,FJSV,GBP(millions),Total,Balances,2012
356,17663,K02000001,2013.0,FJSV,GBP(millions),Total,Balances,2013
357,16811,K02000001,2014.0,FJSV,GBP(millions),Total,Balances,2014
358,14620,K02000001,2015.0,FJSV,GBP(millions),Total,Balances,2015
359,17431,K02000001,2016.0,FJSV,GBP(millions),Total,Balances,2016

In [26]:
new_table = new_table.drop('Year', axis=1)

In [27]:
print(len(new_table))
new_table

360

,OBS,GEOG,Code Identifier,Currency,Insurance Revenue,Commerce,TIME
0,488,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),1997
1,846,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),1998
2,1569,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),1999
3,1423,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2000
4,2182,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2001
5,800,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2002
6,13,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2003
7,-717,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2004
8,-1498,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2005
9,-1261,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2006
10,-526,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2007
11,-264,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2008
12,-619,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2009
13,333,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2010
14,313,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2011
15,429,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2012
16,2842,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2013
17,4056,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2014
18,555,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2015
19,-35,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2016
20,82,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),1997
21,76,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),1998
22,47,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),1999
23,41,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2000
24,49,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2001
25,80,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2002
26,129,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2003
27,90,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2004
28,72,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2005
29,43,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2006
...,...,...,...,...,...,...,...
330,24,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2007
331,-11,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2008
332,-34,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2009
333,,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2010
334,,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2011
335,,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2012
336,,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2013
337,,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2014
338,-3,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2015
339,-4,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2016
340,4431,K02000001,FJSV,GBP(millions),Total,Balances,1997
341,3782,K02000001,FJSV,GBP(millions),Total,Balances,1998
342,2727,K02000001,FJSV,GBP(millions),Total,Balances,1999
343,2250,K02000001,FJSV,GBP(millions),Total,Balances,2000
344,3740,K02000001,FJSV,GBP(millions),Total,Balances,2001
345,3552,K02000001,FJSV,GBP(millions),Total,Balances,2002
346,5025,K02000001,FJSV,GBP(millions),Total,Balances,2003
347,3792,K02000001,FJSV,GBP(millions),Total,Balances,2004
348,8011,K02000001,FJSV,GBP(millions),Total,Balances,2005
349,9570,K02000001,FJSV,GBP(millions),Total,Balances,2006
350,9667,K02000001,FJSV,GBP(millions),Total,Balances,2007
351,11584,K02000001,FJSV,GBP(millions),Total,Balances,2008
352,11184,K02000001,FJSV,GBP(millions),Total,Balances,2009
353,8810,K02000001,FJSV,GBP(millions),Total,Balances,2010
354,12145,K02000001,FJSV,GBP(millions),Total,Balances,2011
355,17814,K02000001,FJSV,GBP(millions),Total,Balances,2012
356,17663,K02000001,FJSV,GBP(millions),Total,Balances,2013
357,16811,K02000001,FJSV,GBP(millions),Total,Balances,2014
358,14620,K02000001,FJSV,GBP(millions),Total,Balances,2015
359,17431,K02000001,FJSV,GBP(millions),Total,Balances,2016

In [28]:
new_table['Insurance Revenue'] = new_table['Insurance Revenue'].map(lambda x: x.rstrip('123'))

In [29]:
new_table

,OBS,GEOG,Code Identifier,Currency,Insurance Revenue,Commerce,TIME
0,488,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),1997
1,846,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),1998
2,1569,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),1999
3,1423,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2000
4,2182,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2001
5,800,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2002
6,13,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2003
7,-717,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2004
8,-1498,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2005
9,-1261,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2006
10,-526,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2007
11,-264,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2008
12,-619,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2009
13,333,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2010
14,313,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2011
15,429,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2012
16,2842,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2013
17,4056,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2014
18,555,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2015
19,-35,K02000001,FJEU,GBP(millions),Life insurance,Exports (Credits),2016
20,82,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),1997
21,76,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),1998
22,47,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),1999
23,41,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2000
24,49,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2001
25,80,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2002
26,129,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2003
27,90,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2004
28,72,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2005
29,43,K02000001,FJJL,GBP(millions),Freight insurance,Exports (Credits),2006
...,...,...,...,...,...,...,...
330,24,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2007
331,-11,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2008
332,-34,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2009
333,,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2010
334,,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2011
335,,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2012
336,,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2013
337,,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2014
338,-3,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2015
339,-4,K02000001,MSH3,GBP(millions),Pensions and standardised guarantees,Balances,2016
340,4431,K02000001,FJSV,GBP(millions),Total,Balances,1997
341,3782,K02000001,FJSV,GBP(millions),Total,Balances,1998
342,2727,K02000001,FJSV,GBP(millions),Total,Balances,1999
343,2250,K02000001,FJSV,GBP(millions),Total,Balances,2000
344,3740,K02000001,FJSV,GBP(millions),Total,Balances,2001
345,3552,K02000001,FJSV,GBP(millions),Total,Balances,2002
346,5025,K02000001,FJSV,GBP(millions),Total,Balances,2003
347,3792,K02000001,FJSV,GBP(millions),Total,Balances,2004
348,8011,K02000001,FJSV,GBP(millions),Total,Balances,2005
349,9570,K02000001,FJSV,GBP(millions),Total,Balances,2006
350,9667,K02000001,FJSV,GBP(millions),Total,Balances,2007
351,11584,K02000001,FJSV,GBP(millions),Total,Balances,2008
352,11184,K02000001,FJSV,GBP(millions),Total,Balances,2009
353,8810,K02000001,FJSV,GBP(millions),Total,Balances,2010
354,12145,K02000001,FJSV,GBP(millions),Total,Balances,2011
355,17814,K02000001,FJSV,GBP(millions),Total,Balances,2012
356,17663,K02000001,FJSV,GBP(millions),Total,Balances,2013
357,16811,K02000001,FJSV,GBP(millions),Total,Balances,2014
358,14620,K02000001,FJSV,GBP(millions),Total,Balances,2015
359,17431,K02000001,FJSV,GBP(millions),Total,Balances,2016

In [30]:
new_table.fillna('', inplace=True)

writetechnicalCSV('C:\\Users\\vamsi\\Desktop\\Gdrive\\Out\\Mret\\pinkbook2017chapter3_3.4.csv', new_table)

writing 1 conversion segments into C:\Users\vamsi\Desktop\Gdrive\Out\Mret\pinkbook2017chapter3_3.4.csv
pdconversionwrite segment size 360